name: Build & Deploy to AWS Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¦ Checkout code
        uses: actions/checkout@v3

      - name: â˜• Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ”§ Build project with Maven
        run: mvn clean package

      - name: ğŸ“ Rename and Zip fat JAR
        run: |
          cd target
          mv springboot-lambda.jar ecommerce-lambda.jar
          zip ecommerce-lambda.zip ecommerce-lambda.jar

      - name: ğŸš€ Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: ecommerce
          region: us-east-1
          zip-file: target/ecommerce-lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
